/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code.challenges;

import code.challenges.hourglass.HourGlass;
import code.challenges.intersections.Intersections;
import code.challenges.linkedlist.AddLinkedListIntegers;

public class App {
    public static void main(String[] args) {
        // HourGlass.findLargestHourGlassSum();
        // Intersections.findIntersectionsProblem();
        AddLinkedListIntegers.AddIntegers();
    }
}
