/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code.challenges;

import code.challenges.hourglass.HourGlass;

public class App {
    public static void main(String[] args) {
        HourGlass.sumHourGlassesFromMatrix();
    }
}
